development:
  adapter: postgresql
  database: danika_kayelle_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: danika_kayelle_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: danika_kayelle_production
  pool: 5
  timeout: 500